name: "Install Chromium"
description: "This action installs the version of Chromium of your choice"
inputs:
  revision:
    description: "Revision"
    required: false
    default: "latest" # integer
  trunk:
    description: "Source"
    required: false
    default: "continuous" # snapshots
runs:
  using: "composite"
  steps:
    - name: Fetch revision from snapshots and install it locally
      shell: bash
      run: |
        if [ "${{ inputs.trunk }}" = "continuous" ]; then
          CHROMIUM_TRUNK="continuous"
        elif [ "${{ inputs.trunk }}" = "snapshots" ]; then
          CHROMIUM_TRUNK="snapshots"
        else
          echo "Unknown trunk (allowed: continuous or snapshots)" >&2
          exit 1
        fi

        if [[ ${OS:-} = Windows_NT ]]; then
          echo "Windows is not yet supported" >&2
          exit 1
        elif [ "$(uname -s)" = "Darwin" ]; then
          if [ "$(uname -m)" = "arm64" ] && [ "${CHROMIUM_TRUNK}" = "snapshots" ]; then
            CHROMIUM_ARCH="Mac_Arm"
          else
            CHROMIUM_ARCH="Mac"
          fi
          CHROMIUM_PLATFORM="mac"
        else
          case $(uname -m) in
          "aarch64" | "arm64")
            if [ "${CHROMIUM_TRUNK}" = "snapshots" ]; then
              CHROMIUM_ARCH="Arm"
            else
              CHROMIUM_ARCH="Linux"
            fi
            ;;
          "x86_64" | "amd64")
            CHROMIUM_ARCH="Linux_x64"
            ;;
          *)
            CHROMIUM_ARCH="Linux"
            ;;
          esac
          CHROMIUM_PLATFORM="linux"
        fi

        echo "Trunk: ${CHROMIUM_TRUNK}, Arch: ${CHROMIUM_ARCH}, Platform: ${CHROMIUM_PLATFORM}"

        CHROMIUM_SNAPSHOT_BASE_URL="https://www.googleapis.com/download/storage/v1/b/chromium-browser-$CHROMIUM_TRUNK/o/$CHROMIUM_ARCH"

        web() {
        local list="wget curl"
        for item in $list;
        do
          if [ -z $(command -v $item) ]; then
            echo $list | sed "s/$item//g"
          fi
        done
        }

        dl() {
        case $(web) in
          *wget*) wget -q -O $@;;
          *curl*) curl -#L -o $@;;
        esac
        }

        out() {
        case $(web) in
          *curl*) curl --fail -sL $@;;
          *wget*) wget -qO - $@;;
        esac
        }

        if [ "${{ inputs.revision }}" = "latest" ]; then
          CHROMIUM_LASTCHANGE_URL="$CHROMIUM_SNAPSHOT_BASE_URL%2FLAST_CHANGE?alt=media"
          CHROMIUM_REVISION=$(out $CHROMIUM_LASTCHANGE_URL)
          echo "DEBUG CHROMIUM_LASTCHANGE_URL: $CHROMIUM_LASTCHANGE_URL"
          echo "DEBUG CHROMIUM_REVISION: '$CHROMIUM_REVISION'"
          if test -z "$CHROMIUM_REVISION"; then
            echo "Failed to fetch the latest revision number." >&2
            exit 1
          fi
          echo "Using latest revision: $CHROMIUM_REVISION"
        else
          CHROMIUM_REVISION="${{ inputs.revision }}"
          echo "Using specified revision: $CHROMIUM_REVISION"
        fi

        CHROMIUM_SNAPSHOT_ZIP_URL="$CHROMIUM_SNAPSHOT_BASE_URL%2F$CHROMIUM_REVISION%2Fchrome-$CHROMIUM_PLATFORM.zip?alt=media"
        CHROMIUM_INSTALL_TMP_DIR="/tmp/chromium-$CHROMIUM_REVISION"

        echo "Downloading Chromium snapshot..."
        rm -rf "$CHROMIUM_INSTALL_TMP_DIR"
        mkdir -p "$CHROMIUM_INSTALL_TMP_DIR" || {
          echo "Failed to create install directory \"$CHROMIUM_INSTALL_TMP_DIR\"" >&2
          exit 1
        }

        CHROMIUM_SNAPSHOT_ZIP_FILE="chrome-$CHROMIUM_PLATFORM-$CHROMIUM_REVISION.zip"
        dl "$CHROMIUM_SNAPSHOT_ZIP_URL" "$CHROMIUM_INSTALL_TMP_DIR/$CHROMIUM_SNAPSHOT_ZIP_FILE" || {
          echo "Failed to download Chromium snapshot." >&2
          exit 1
        }

        echo "Unzipping Chromium snapshot..."
        command -v unzip >/dev/null || {
          echo "You need to install \"unzip\" first!"
          exit 1
        }

        unzip -foqq "$CHROMIUM_INSTALL_TMP_DIR/$CHROMIUM_SNAPSHOT_ZIP_FILE" -d "$CHROMIUM_INSTALL_TMP_DIR" || {
          echo "Failed to unzip Chromium snapshot." >&2
          exit 1
        }

        echo "Chromium extracted to $CHROMIUM_INSTALL_TMP_DIR/chrome-$CHROMIUM_PLATFORM"
        CHROMIUM_INSTALL_DIR_PATH=$PWD/chromium-bin
        ln -fs "$CHROMIUM_INSTALL_TMP_DIR/chrome-$CHROMIUM_PLATFORM $CHROMIUM_INSTALL_DIR_PATH

        echo "Changing owner and permissions for chrome_sandbox (requires privileges):\n"
        sudo chown root:root "$CHROMIUM_INSTALL_DIR_PATH/chrome_sandbox"
        sudo chmod 4755 "$CHROMIUM_INSTALL_DIR_PATH/chrome_sandbox"

        echo "CHROMIUM_INSTALL_DIR_PATH=$CHROMIUM_INSTALL_DIR_PATH" >> $GITHUB_ENV
