name: CI local

on: {}

jobs:
  run_local:
    name: Run local
    strategy:
      fail-fast: true
      matrix:
        trunk: [continuous, snapshots]
        include:
          - trunk: continuous
            platform: ubuntu:latest
          - trunk: snapshots
            platform: ubuntu:latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: 📥 Checkout Git Code
        uses: actions/checkout@v4
      - name: 📦 Install Chromium Package
        uses: ./
        with:
          revision: "latest"
          trunk: ${{ matrix.trunk }}
      - name: 🧪 Output CHROMIUM_DIRECTORY and CHROMIUM_BIN
        shell: bash
        run: |
          echo "Chromium direction path: \"$CHROMIUM_DIRECTORY\""
          echo "Chromium binary path: \"$CHROMIUM_BIN\""
