name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths-ignore: ["**.md"]
  push:
    branches: [main]
    paths-ignore: ["**.md"]

# concurrency:
#   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.pull_request.head.ref || github.head_ref || github.ref }}
#   cancel-in-progress: true

# permissions:
#   contents: read

jobs:
  run:
    name: Run
    # strategy:
    #   fail-fast: true
    #   matrix:
    #     trunk: [continuous, snapshots]
    #     include:
    #       - trunk: continuous
    #         # platforms: ["i386/ubuntu:latest", "ubuntu:latest", "Mac"]
    #         # platforms: ["i386/ubuntu:latest", "ubuntu:latest", "mac-latest"]
    #         platforms: ["buildjet-2vcpu-ubuntu-2204"]
    #       - trunk: snapshots
    #         # platforms: ["Arm", "i386/ubuntu:latest", "ubuntu:latest", "Mac", "Mac-Arm"]
    #         # platforms: ["i386/ubuntu:latest", "ubuntu:latest", "mac-latest"]
    #         platforms: ["buildjet-2vcpu-ubuntu-2204"]
    # runs-on: ${{ matrix.platforms }}
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - name: 📥 Checkout Git Code
        uses: actions/checkout@v4
      - name: 📦 Install Chromium Package
        uses: ./
        with:
          revision: "latest"
          trunk: ${{ matrix.trunk }}
      - name: 🧪 Output CHROMIUM_BIN
        shell: bash
        run: |
          echo "Chromium binary path: $CHROMIUM_BIN"
