name: Tests (local with act tool)

on: {}

jobs:
  act:
    name: act
    runs-on: ${{ env.act_image_modified }}
    steps:
      - name: 📥 Checkout Git Code
        uses: actions/checkout@v4
      - name: 📦 Install Chromium Package
        uses: ./
        with:
          revision: "latest"
          trunk: ${{ env.chromium_trunk }}
      - name: 🧪 Output CHROMIUM_DIRECTORY and CHROMIUM_BIN
        shell: bash
        run: |
          echo "CHROMIUM_DIRECTORY=$CHROMIUM_DIRECTORY"
          echo "CHROMIUM_BIN=$CHROMIUM_BIN"
      - name: 💎 Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
      - name: 💎 Run rails dummy app to test Chromium
        env:
          CI: true
          RAILS_ENV: test
          NODE_ENV: test
          RAKE_ENV: test
        run: |
          ruby --version
          ruby scripts/system_tests.rb
